### ISSUE TITLE
Errors when callbacks are not specified

### ISSUE THREAD

**Issue by stropitek** [Git-me-outta-here/react-parallel-coordinates#2]
When callbacks like `onLineHover`, or `onBrush_extents` (or any other callback I think) are not given as props, it tries to invoke it anyway and thus generates an error.

**Comment by Git-me-outta-here** [comment]
I'm glad to see someone's using this and reporting issues. I think you are right with all of them. I'll get to fixing 👍

**Comment by stropitek** [comment]
Good, if you need any help I can make PRs
